domain:    s.minos.io
port:      80
wwwroot:   /var/www/s.minos.io/
buildroot: /home/admin/minos-static
cdn:       https://cdn.jsdelivr.net/gh/minos-org/minos-static@de7ceb083fb1945c9861185e43cb869121c098e7/static-get
